services:
  dev-retrostore-frontend:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules # <-- prevents node_modules from being overridden
    command: npm start
