FROM node:20

#ENV NODE_OPTIONS=--openssl-legacy-provider

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV REACT_APP_ENV=production

RUN npm run build 
#--verbose

RUN npm i -g serve  

CMD [ "serve", "-s", "build" ]