services:
  prod-spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      db_url: ${prod_db_url}
      db_username: ${db_username}
      db_password: ${db_password}
  prod-spring-boot-postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    #ports:
    #  - "5432:5432"
  prod-retrostore-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
volumes:
  pgdata: