services:
  dev-spring-boot-app:
    build: .
    ports:
      - "8081:8081"
    environment:
      db_url: ${dev_db_url}
      db_username: ${db_username}
      db_password: ${db_password}
  dev-spring-boot-postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    #ports:
    #  - "5432:5432"
  dev-retrostore-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    #  - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
volumes:
  pgdata: